# Schema for the configuration files of the demotask module.
demotask.settings:
  type: config_object
  label: 'demotask settings'
  mapping:
    title:
      type: string
      label: 'Title'
    text:
      type: text
      label: 'Text'
    format:
      type: string
      label: 'Format'
    display:
      type: boolean
      label: 'Display'

